name: my_flutter_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animate_do: ^3.0.2
  vibration: ^1.7.5
  fl_chart: ^0.64.0
  uuid: ^4.2.1
  image_picker: ^0.8.4+4
  provider: ^6.0.0
  intl: ^0.18.0
  shared_preferences: ^2.0.0
  flutter_spinkit: ^5.2.0
  http: ^1.1.0
  google_generative_ai: ^0.2.0
  confetti: ^0.7.0
  just_audio: ^0.9.36
  video_player: ^2.7.0
  cached_network_image: ^3.2.3
  lottie: ^2.6.0
  flutter_animate: ^4.2.0
  audio_session: ^0.1.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/splash.png
    - lib/assets/images/loginsignup.png
    - lib/assets/images/login.png
    - lib/assets/images/google.png
    - lib/assets/images/facebook.png
    - lib/assets/images/apple.png
    - lib/assets/images/graph.png
    - lib/assets/images/brainperson.png
    - lib/assets/images/Trust.png
    - lib/assets/images/sendmoney.png
    - lib/assets/images/receivemoney.png
    - lib/assets/images/backgroundhex.png
    - lib/assets/images/mind.png
    - lib/assets/images/patient.png
    - lib/assets/images/reminder.png
    - lib/assets/images/story.png
    - lib/assets/images/memoraid.png
    - lib/assets/images/kushen.png
    - lib/assets/images/spot1.jpeg
    - lib/assets/images/spot2.jpeg
    - lib/assets/images/crow1.jpeg
    - lib/assets/images/crow2.jpeg
    - lib/assets/images/Family.jpeg
    - lib/assets/images/Mansion.jpeg
    - lib/assets/images/MarsMission.jpeg
    - lib/assets/images/Rainforest.jpeg
    - lib/assets/images/ArcticExpedition.jpeg
    - lib/assets/images/Traveler.jpeg
    - lib/assets/images/RiversCrossing.jpeg
    - lib/assets/images/dog1.jpeg
    - lib/assets/images/dog2.jpeg
    - lib/assets/images/plane1.jpeg
    - lib/assets/images/plane2.jpeg
    - lib/assets/images/cow1.jpeg
    - lib/assets/images/cow2.jpeg
    - lib/assets/images/boy1.jpeg
    - lib/assets/images/boy2.jpeg
    - lib/assets/images/no.png
    - lib/assets/images/CrossBody.webp
    - lib/assets/images/yoga.jpeg
    - lib/assets/images/hand.webp
    - lib/assets/images/relax.png
    - lib/assets/audio/Story1.mp3
    - lib/assets/audio/Story2.mp3
    - lib/assets/audio/Story3.mp3
    - lib/assets/audio/Story5.mp3
    - lib/assets/audio/Story7.mp3
    - lib/assets/audio/Story8.mp3
    - lib/assets/audio/Story9.mp3
