name: my_flutter_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animate_do: ^3.0.2
  vibration: ^1.7.5
  fl_chart: ^0.64.0
  uuid: ^4.2.1
  image_picker: ^0.8.4+4
  provider: ^6.0.0
  intl: ^0.18.0
  shared_preferences: ^2.0.0
  flutter_spinkit: ^5.2.0
  http: ^1.1.0
  google_generative_ai: ^0.2.0
  confetti: ^0.6.0
  just_audio: ^0.9.35
  audio_session: ^0.1.16
  speech_to_text: ^6.3.0
  google_mlkit_face_detection: ^0.8.0
  camera: ^0.10.5+4
  geolocator: ^10.1.0
  url_launcher: ^6.1.14
  permission_handler: ^11.0.1
  flutter_animate: ^4.1.1
  flutter_local_notifications: ^16.1.0
  timezone: ^0.9.2
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/splash.png
    - lib/assets/images/loginsignup.png
    - lib/assets/images/login.png
    - lib/assets/images/google.png
    - lib/assets/images/facebook.png
    - lib/assets/images/apple.png
    - lib/assets/images/graph.png
    - lib/assets/images/brainperson.png
    - lib/assets/images/Trust.png
    - lib/assets/images/sendmoney.png
    - lib/assets/images/receivemoney.png
    - lib/assets/images/backgroundhex.png
    - lib/assets/images/mind.png
    - lib/assets/images/patient.png
    - lib/assets/images/reminder.png
    - lib/assets/images/story.png
    - lib/assets/images/memoraid.png
    - lib/assets/images/kushen.png
    - lib/assets/images/spot1.jpeg
    - lib/assets/images/spot2.jpeg
    - lib/assets/images/crow1.jpeg
    - lib/assets/images/crow2.jpeg
